# Generated by Django 2.0 on 2017-12-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineChartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('dayOfWeek', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'linechartdata',
            },
        ),
    ]
