# Generated by Django 2.0 on 2017-12-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fail2banNgStatsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BansTableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jail', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('timeofban', models.IntegerField()),
                ('bantime', models.IntegerField()),
            ],
            options={
                'db_table': 'banstabledata',
            },
        ),
        migrations.AddField(
            model_name='linechartdata',
            name='code',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
    ]
