# Generated by Django 2.0 on 2018-01-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fail2banNgStatsApp', '0002_auto_20171220_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('banscount', models.IntegerField()),
            ],
            options={
                'db_table': 'locationtabledata',
            },
        ),
    ]
