# Generated by Django 2.0 on 2018-01-07 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fail2banNgStatsApp', '0004_auto_20180105_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtabledata',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
