# Generated by Django 2.0 on 2018-01-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fail2banNgStatsApp', '0005_locationtabledata_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtabledata',
            name='dayOfTheWeek',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
    ]
