# Generated by Django 2.0 on 2018-09-10 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Fail2banNgStatsApp', '0008_lastrefreshtabledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='banstabledata',
            name='timeOfArrival',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
